#!/usr/bin/env python3
"""Derive the animated marks from the static ones.

    python3 brand/animate-mark.py

For each static mark, writes two files beside it:

- <name>-animated.svg — the loops trade sizes once and back every twelve
  seconds. For a header: alive, never busy.
- <name>-loading.svg  — the loops trade steadily, 2.8s a round trip. For
  anything that is working: loading, sending, "one moment".

The motion is the warp in BRAND.md §8: the small loop swells into the big one
while the big one draws in, and the gold dot rides through the crossing into
whichever loop is small. The pages build the same thing inline from
services/voice/src/signup/mascot.ts, which can also honour a reader's request
for less motion; these files cannot, so a page that uses one shows the static
mark under `prefers-reduced-motion: reduce`.

Why a warp works where a morph against the mirror image did not: the second
drawing here is traced in the same order as the first — left loop, then right,
each from the crossing, over the top, round and back — so every point moves
within its own loop and every in-between frame is a real infinity. Morphing
against the plain mirror pairs each loop with the other one, and halfway every
x lands on the axis.

Generated, not hand-kept, so the moving mark cannot drift from the still one.
"""
import re
from pathlib import Path

SRC = Path(__file__).resolve().parent / 'assets'
NOTE = ('<!-- Generated by brand/animate-mark.py from the static mark. Do not hand-edit: '
        'regenerate it, or the two drawings drift. -->')
EASE = '0.45 0 0.55 1'
TIMING = {
    'animated': ([0, 0.8, 0.9, 1], [0, 0, 1, 0], 12),
    'loading': ([0, 0.5, 1], [0, 1, 0], 2.8),
}


def traded(d: str) -> tuple[str, float]:
    """The path with its loops traded, traced in the same order, and the axis."""
    n = [float(v) for v in re.findall(r'-?[\d.]+', d)]
    if len(n) != 2 + 8 * 6 or not d.startswith('M') or d.count('C') != 8:
        raise SystemExit('expected the mark as M plus eight cubics, two loops of four')
    xs = n[0::2]
    axis = (min(xs) + max(xs)) / 2
    pt = lambda i: f'{2 * axis - n[i]:g} {n[i + 1]:g}'
    seg = lambda k: f'C{pt(2 + k * 6)} {pt(4 + k * 6)} {pt(6 + k * 6)}'
    return f'M{pt(0)}' + ''.join(seg(k) for k in (4, 5, 6, 7)) + ''.join(seg(k) for k in (0, 1, 2, 3)) + 'Z', axis


def animate(attr: str, a: str, b: str, kind: str) -> str:
    times, at, dur = TIMING[kind]
    values = ';'.join((a, b)[i] for i in at)
    splines = ';'.join(EASE for _ in times[1:])
    return (f'<animate attributeName="{attr}" dur="{dur:g}s" repeatCount="indefinite" calcMode="spline" '
            f'keyTimes="{";".join(f"{t:g}" for t in times)}" keySplines="{splines}" values="{values}"/>')


for name in ('mark', 'mark-on-night', 'mark-on-gold', 'mark-badge'):
    f = SRC / f'{name}.svg'
    if not f.exists():
        continue
    svg = f.read_text()
    path = re.search(r'<path d="([^"]+)"([^>]*)/>', svg)
    dot = re.search(r'<circle cx="([\d.]+)" cy="([\d.]+)" r="([\d.]+)" fill="(#\w+)"/>\s*</svg>', svg)
    if not (path and dot):
        raise SystemExit(f'{f} is not the drawing this script knows how to animate')
    other, axis = traded(path.group(1))
    here, there = dot.group(1), f'{2 * axis - float(dot.group(1)):g}'
    for kind in TIMING:
        out = svg.replace(
            path.group(0),
            f'<path d="{path.group(1)}"{path.group(2)}>{animate("d", path.group(1), other, kind)}</path>',
        ).replace(
            dot.group(0),
            f'<circle cx="{here}" cy="{dot.group(2)}" r="{dot.group(3)}" fill="{dot.group(4)}">'
            f'{animate("cx", here, there, kind)}</circle></svg>',
        )
        out = out.replace('</title>', f'</title>{NOTE}', 1)
        (SRC / f'{name}-{kind}.svg').write_text(out)
        print(f'{name}-{kind}.svg')
