#!/usr/bin/env python3
"""Derive the animated marks from the static ones.

    python3 brand/animate-mark.py

Writes brand/assets/<name>-animated.svg for every mark that has one. The
animation is a half turn rather than a morph between the mark and its mirror:
interpolating those two collapses every x onto the axis at the midpoint and the
mark becomes a vertical bar. Turning keeps the real drawing in every frame, and
passes through the upright 8 on the way.

Generated, not hand-kept, so the moving mark cannot drift from the still one.
"""
import re
from pathlib import Path
SRC = Path(__file__).resolve().parent / 'assets'

NOTE = ('<!-- Generated by brand/animate-mark.py from the static mark. Do not hand-edit: '
        'regenerate it, or the two drawings drift. -->')

for name in ('mark', 'mark-on-night', 'mark-on-gold', 'mark-badge'):
    f = SRC / f'{name}.svg'
    if not f.exists():
        continue
    svg = f.read_text()
    vb = [float(v) for v in re.search(r'viewBox="([^"]+)"', svg).group(1).split()]
    cx, cy = vb[0] + vb[2] / 2, vb[1] + vb[3] / 2

    # A square box, centred on the same point.
    #
    # The static mark is wider than it is tall, which is correct for a mark that
    # lies down. Turned a quarter of the way it needs its own width in height,
    # and the first version of this clipped the loops flat at the top and bottom
    # every nine seconds. The animated file is therefore square and the static
    # one is not — anything laying them out should size by width and let the
    # height follow.
    half = max(vb[2], vb[3]) / 2
    square = f'{cx-half:g} {cy-half:g} {half*2:g} {half*2:g}'
    svg = svg.replace(re.search(r'viewBox="([^"]+)"', svg).group(0), f'viewBox="{square}"')

    # A half turn, not a morph.
    #
    # The obvious way to swap the loops is to interpolate the path against its
    # own mirror. It does not work: every x converges on the axis at the
    # midpoint and the mark collapses into a vertical bar. Rotating is the
    # same destination — a lopsided infinity is near enough symmetric about its
    # own waist that half a turn lands on the mirror — and every frame in
    # between is the real drawing rather than an average of two.
    #
    # It also passes through the upright 8 at a quarter turn, which is the
    # figure the name is written in.
    #
    # Nine seconds a half turn, with a hold at each end. SCRIPT.md spends a
    # whole call refusing to manufacture urgency; a mark that spins is a mark
    # that nags.
    anim = (f'<animateTransform attributeName="transform" type="rotate" dur="18s" '
            f'repeatCount="indefinite" calcMode="spline" '
            f'keyTimes="0;0.22;0.5;0.72;1" '
            f'keySplines="0.45 0 0.2 1;0 0 1 1;0.45 0 0.2 1;0 0 1 1" '
            f'values="0 {cx:g} {cy:g};180 {cx:g} {cy:g};180 {cx:g} {cy:g};'
            f'360 {cx:g} {cy:g};360 {cx:g} {cy:g}"/>')

    # One group around everything, so the line and the dot turn together.
    body = re.sub(r'^.*?</title>', '', svg, flags=re.S).replace('</svg>', '')
    head = re.match(r'^.*?</title>', svg, flags=re.S).group(0)
    out = f'{head}{NOTE}<g>{anim}{body}</g></svg>'
    (SRC / f'{name}-animated.svg').write_text(out)
    print(f'{name}-animated.svg')
